spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:files}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}

aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT}
    bucket: ${AWS_S3_BUCKET}
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}