spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}
cloud-config-verify: cloud-local

app:
  frontend:
    host: ${APP_FRONTEND_HOST:http://localhost:3001}
