spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:notifications}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}

rabbitmq:
  host: ${RABBIT_HOST:rabbitmq}

notifications:
  retry:
    maxAttempts: 5
