spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:product}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}

rabbitmq:
  host: ${RABBIT_HOST:rabbitmq}
