spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:livecom}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}

  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:admin}
    password: ${RABBIT_PASS:admin123}

app:
  otp.provider: mock
  jwt.secret: ${APP_JWT_SECRET:}
  openapi.dev-url: http://localhost:8080

  frontend:
    host: ${APP_FRONTEND_HOST:http://localhost:3001}

cloud-config-verify: cloud-local
